services:
  postgres_db:
    image: postgres:14.1-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tech_zoneDB
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: TechZoneDB
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  postgres_data:
  mysql_data: